# Generated by Django 3.0.1 on 2019-12-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzza',
            fields=[
                ('id_pizzy', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('skladniki', models.CharField(blank=True, max_length=255, null=True)),
                ('rozmiar', models.IntegerField(blank=True, null=True)),
                ('cena', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pizzza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('zamowienia', models.IntegerField(blank=True, null=True)),
                ('id_zamowienia', models.AutoField(primary_key=True, serialize=False)),
                ('pizza', models.CharField(blank=True, max_length=255, null=True)),
                ('lokal', models.IntegerField(blank=True, null=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=9)),
                ('mail', models.CharField(max_length=30)),
                ('adres', models.CharField(max_length=40)),
                ('uwagi', models.CharField(max_length=250)),
                ('platnosc', models.IntegerField()),
                ('numerkarty', models.CharField(blank=True, db_column='numerKarty', max_length=20, null=True)),
                ('cvv', models.CharField(blank=True, db_column='CVV', max_length=3, null=True)),
                ('mmrr', models.CharField(blank=True, db_column='MMRR', max_length=20, null=True)),
                ('cena', models.FloatField()),
            ],
            options={
                'db_table': 'zamowienia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lokal',
            fields=[
                ('nazwa_lokalu', models.CharField(blank=True, max_length=50, null=True)),
                ('id_lokalu', models.OneToOneField(db_column='id_lokalu', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='lokalSet', serialize=False, to='pizzeria.Zamowienia')),
                ('miasto', models.CharField(blank=True, max_length=20, null=True)),
                ('cenadostawy', models.CharField(blank=True, max_length=50, null=True)),
                ('adres', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lokal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=70, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('rola', models.CharField(max_length=20)),
                ('zamowienia', models.OneToOneField(blank=True, db_column='zamowienia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pizzeria.Zamowienia')),
            ],
            options={
                'db_table': 'uzytkownicy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LokalPizzzaLaczaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pizzy', models.ForeignKey(db_column='id_pizzy', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzeria.Pizzza')),
                ('id_lokalu', models.ForeignKey(db_column='id_lokalu', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzeria.Lokal')),
            ],
            options={
                'db_table': 'lokal_pizzza_laczaca',
                'managed': True,
            },
        ),
    ]
